apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/default-backend: {{ .Chart.Name }}-svc
spec:
  rules:
    - host: {{ .Values.simplewebserver.ingress.domain }}
      http:
        paths:
          -
            backend:
              service:
                name: {{ .Chart.Name }}-svc
                port:
                  number: {{ .Values.simplewebserver.service.port }}
            path: /
            pathType: "Prefix"
