apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.simplewebserver.service.type }}
  selector:
    {{- toYaml .Values.simplewebserver.labels | nindent 4 }}
  ports:
    - port: {{ .Values.simplewebserver.service.port }}
      targetPort: {{ .Values.simplewebserver.service.port }}
